# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/hand_pose',
                'doc_host': 'https://benjaminserrano23.github.io',
                'git_url': 'https://github.com/benjaminserrano23/hand_pose',
                'lib_path': 'hand_pose'},
  'syms': {'hand_pose.core': {'hand_pose.core.foo': ('core.html#foo', 'hand_pose/core.py')}}}
